-- Remove specific transaction ID from used transactions and payment verification logs
-- Generated by Antigravity at request of user to remove transaction 417214489231417345

DELETE FROM public.used_transactions 
WHERE transaction_id = '417214489231417345';

DELETE FROM public.payment_verification_logs 
WHERE transaction_id = '417214489231417345';
